"""Create initial tables

Revision ID: 4b5e3d48bd0e
Revises: 
Create Date: 2023-12-18 17:54:08.696027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b5e3d48bd0e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bitcoin_address",
        sa.Column(
            "id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True
        ),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=True, default=0.0),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index(
        "ix_bitcoin_address_address", "bitcoin_address", ["address"], unique=False
    )

    op.create_table(
        "transaction",
        sa.Column(
            "id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True
        ),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("receiver", sa.String(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column(
            "bitcoin_address_id",
            sa.Integer(),
            sa.ForeignKey("bitcoin_address.id"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index on the 'address' column of the 'bitcoin_address' table
    op.drop_index("ix_bitcoin_address_address", table_name="bitcoin_address")

    op.drop_table("transaction")
    op.drop_table("bitcoin_address")
    # ### end Alembic commands ###
